### ISSUE TITLE
scripts in body

### ISSUE THREAD

**Issue by ilias-t** [jenmcphail/hangman-browser-game#6]
consider moving your [scripts](https://github.com/jenmcphail/hangman-browser-game/blob/27b7ec20dbcbe989ea5775f79224af005d26c361/index.html#L51-L53) to the head. As long as you're using `window.onload` it shouldn't change the behavior. Rather it will load the scripts quicker as it will not wait for window to load to fetch the scripts.

**Comment by jenmcphail** [comment]
@iliastsangaris unfortunately, moving the scripts up to the head broke the code. The console showed an error that it was unable to "append child of undefined" on line 67. Seems like it's trying to create the board before the window loads? Not sure why since I'm creating the board within the init function and only calling the init function on window.onload. Moving them back in to body got it working again.
